version: 2.1

parameters:
  trigger_world_greeting:
    type: boolean
    default: false

jobs:
  greet_world:
    machine:
      image: ubuntu-2004:202010-01
      steps:
        - run: echo "Hello, world!"

  greet_universe:
    machine:
      image: ubuntu-2004:202010-01
      steps:
        - run: echo "Hello, universe!"

workflows:
  version: 2

  says_hello_world:
    jobs:
      - greet_world
    when:
      or:
        - equal: [ master, << pipeline.git.branch >> ]
        - << pipeline.parameters.trigger_world_greeting >>

  says_hello_universe:
    jobs:
      - greet_universe
